# Generated by Django 2.2.1 on 2019-05-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_handle', models.CharField(max_length=200)),
                ('signup_date', models.DateTimeField(verbose_name='signup date')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='read_only_site.Player')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='read_only_site.Player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='read_only_site.Player')),
            ],
        ),
    ]
