# Generated by Django 2.2.1 on 2019-05-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_only_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_trueskill_mu_after_match',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_trueskill_mu_before_match',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_trueskill_sigma_after_match',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_trueskill_sigma_before_match',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_trueskill_mu_after_match',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_trueskill_mu_before_match',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_trueskill_sigma_after_match',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_trueskill_sigma_before_match',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='trueskill_mu',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='player',
            name='trueskill_sigma',
            field=models.FloatField(default=8.333),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_handle',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
