# Generated by Django 2.2.1 on 2019-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_only_site', '0002_auto_20190531_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_trueskill_mu_after_match',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_trueskill_mu_before_match',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_trueskill_sigma_after_match',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_trueskill_sigma_before_match',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_trueskill_mu_after_match',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_trueskill_mu_before_match',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_trueskill_sigma_after_match',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_trueskill_sigma_before_match',
            field=models.FloatField(blank=True),
        ),
    ]
