# Generated by Django 2.2.1 on 2019-05-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_only_site', '0003_auto_20190531_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_id',
            new_name='match_identifier',
        ),
    ]
