# Generated by Django 2.2.1 on 2019-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_only_site', '0004_auto_20190531_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_identifier',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
