# Generated by Django 2.2.1 on 2019-06-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_only_site', '0006_auto_20190601_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='trueskill_mu',
            field=models.FloatField(default=300.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='trueskill_sigma',
            field=models.FloatField(default=200.0),
        ),
    ]
