# Generated by Django 2.2.1 on 2019-06-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_only_site', '0008_player_jstris_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jstris_handle',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
