# Generated by Django 2.2.1 on 2019-06-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_only_site', '0009_auto_20190606_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_nickname',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='jstris_handle',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
