# Generated by Django 2.2.2 on 2019-07-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_only_site', '0010_auto_20190607_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='trueskill_sigma',
            field=models.FloatField(default=100.0),
        ),
    ]
