# Generated by Django 2.2.2 on 2019-07-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_only_site', '0011_auto_20190702_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
